### ISSUE TITLE
Change SzDatasourceError to SzDataSourceError

### ISSUE THREAD

**Issue by barrycaceres** [senzing-garage/knowledge-base#87]
For Senzing the term Data Source is considered to be two words as in `DATA_SOURCE` for the Json tag we use.

This is also reflected in the "Canonical Names"  document for V4 with the following
- `dataSourceCode` parameter names
- `addDataSource()` function
- `getDataSources()` function

I believe `SzDatasourceError` has an error in capitalization and should therefore be `SzDataSourceError`.

Can we update the errors document to reflect that?

https://github.com/senzing-garage/knowledge-base/blob/main/proposals/SDKs-for-V4/error-messages.md

I don't know if there are any other stray places that were are using `Datasource` without the capitalization on the `S`

**NOTE**: The same mis-capitalization is also in this JSON file in the `sz-sdk-errors` repository:

https://github.com/senzing-garage/sz-sdk-errors/blob/main/szerrors.json

**Comment by docktermj** [comment]
Fixed in 

- https://github.com/senzing-garage/sz-sdk-errors/blob/751b9ef4fe9808d760d55dd6cc449e6c5c5f3194/szerrors.json#L1054
- https://github.com/senzing-garage/knowledge-base/blob/main/proposals/SDKs-for-V4/error-messages.md
